spring.application.name=backend

# -----------------------------
# CONFIGURACIÓN DEL SERVIDOR
# -----------------------------
server.port=9090

# -----------------------------
# CONEXIÓN A BASE DE DATOS RDS
# -----------------------------
spring.datasource.url=jdbc:mysql://huertohogar-db.c32uasyiwykf.us-east-1.rds.amazonaws.com:3306/huertohogar_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=DJBenito200405
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -----------------------------
# JPA / HIBERNATE
# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# -----------------------------
# SWAGGER (OpenAPI)
# -----------------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# =========================================
# CONFIGURACIÓN JWT
# =========================================
app.jwt.secret=12345678901234567890123456789012
app.jwt.expirationMs=3600000
